name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '* #$NUMBER $TITLE'
template: |
  $CHANGES

  ## Contributors

  $CONTRIBUTORS
categories:
  - title: '💥 Breaking'
    labels:
      - breaking
  - title: '✨ Features'
    labels:
      - feature
      - enhancement
  - title: '🐛 Bug Fixes'
    labels:
      - bug
  - title: '👷 Maintenance'
    labels:
      - chore
  - title: '📝 Documentation'
    labels:
      - docs
  - title: '📦 Dependency Updates'
    labels:
      - 'dependency'
exclude-labels:
  - 'skip-changelog'
version-resolver:
  # Uncomment when ready for release, and remove 'breaking' from minor
  # major:
  #   labels:
  #     - 'breaking'
  minor:
    labels:
      - 'breaking'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'chore'
      - 'bug'
      - 'docs'
      - 'dependency'
  default: patch
