name: PR Label Checker

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_pull_request_type:
    name: Check PR labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: breaking,feature,enhancement,chore,bug,docs,dependency
          repo_token: ${{ secrets.GITHUB_TOKEN }}
